#!/usr/bin/env bash
#transfer file from client to server
#scp -i "$Path_transferred" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
