#!/usr/bin/env bash
#redirection file
#return an HTTP 404 error code
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
