#!/usr/bin/env bash
#Fixing the container
.
pkill nginx
pkill apache
chown -R nginx:nginx /etc/nginx
sudo chmod +r /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
