#!/usr/bin/env bash
#fix_in_7_lines_or_less
pkill apache
chown -R nginx:nginx /etc/nginx
sudo chmod +r /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
